services:
  backend:
    container_name: nestjs_backend
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    # tty: set up a pseudo-tty to keep the container running
    # using it or command: [ "yarn", "start:dev" ]
    tty: true
    # command: [ "yarn", "start:dev" ]
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - ${BACKEND_PORT}:9100
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
